package wizard_team.wizards_tale.appwarp_listeners;

public enum RoomRequestEventType implements EventType {
    UNSUBSCRIBE_ROOM_DONE, JOIN_ROOM_DONE, LEAVE_ROOM_DONE, GET_LIVE_ROOM_INFO, SET_CUSTOM_ROOM_DATA, UPDATE_PROPERTY_DONE, JOIN_AND_SUBSCRIBE, LEAVE_AND_UNSUBSCRIBE, SUBSCRIBE_ROOM_DONE

}
